config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users
  resources :categories
  resources :payments
  resources :splash, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
end

app/models/payment.rb
class Payment < ApplicationRecord
  has_and_belongs_to_many :categories
  belongs_to :user

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, numericality: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]
  load_and_authorize_resource
  before_action :authenticate_user!

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id

    respond_to do |format|
      if @payment.save
        format.html { redirect_to categories_path, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, category_ids: [])
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, class: "w-full mt-10 flex flex-col items-center gap-2") do |form| %>
  <div class="w-full">
    <%= form.text_field :name, placeholder: "Transaction name", class: "w-full p-3" %>
  
    <%= form.text_field :amount, placeholder: "Transaction amount", class: "mt-2 w-full p-3" %>

    <%= form.collection_select :category_ids, Category.all, :id, :name, { include_blank: false }, { multiple: true, class: " mt-2 w-full p-3" } %>
  </div>

  <% if payment.errors.any? %>
    <div class="w-full h-fit p-4 bg-red-400  text-white">
      <h2><%= pluralize(payment.errors.count, "error") %> found:</h2>

      <ul class="list-disc list-inside">
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="absolute bottom-0 w-full text-center bg-[#5fb523] p-4 text-white">
    <div class="w-full border-[1px] border-white py-4 cursor-pointer">
      <%= form.submit "Save", class: "w-full text-lg cursor-pointer" %>
    </div>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

  <p>
    <strong>User:</strong>
    <%= payment.user_id %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<div class="min-h-screen relative">
  <header class="w-full p-3 bg-[#3778c2] text-white text-lg flex justify-between">
    <nav>
      <a onclick="history.back()"><i class="fa-solid fa-chevron-left fa-lg"></i></a>
    </nav>
    <h1 class="ml-[-15px]">NEW TRANSACTION<h1>
    <span></span>
  </header>
  <%= render "form", payment: @payment %>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>