config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users
  resources :categories
  resources :payments
  resources :splash, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "categories#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :payments
  belongs_to :user

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:payments).where(user_id: current_user.id)
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="flex gap-3 items-center" id="<%= dom_id category %>">
  <div class="bg-white w-[80px] h-[80px] flex justify-center items-center border-[1px] border-slate-200">
    <img class="w-full" src="<%= category.icon %>" alt="<%= category.name %> Category"/>
  </div>
  <div class="grow">
    <div class="flex justify-between items-center">
      <p class="font-bold text-gray-500"><%= category.name %></p>
      <p class="font-bold">
        $<%= category.payments.inject(0) { |sum, e| sum + (e.amount) }%>
      </p>
    </div>
    <p class="text-gray-300 text-sm"><%= category.created_at.strftime("%d %b %Y") %></p>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "w-full mt-10 flex flex-col items-center gap-2") do |form| %>
  
  <div class="w-full">
    <%= form.text_field :name, placeholder: 'Category name', class: "w-full p-3" %>
    <%= form.text_field :icon, placeholder: 'Image path', class: "mt-2 w-full p-3" %>
  </div>

  <% if category.errors.any? %>
    <div class="w-full h-fit p-4 bg-red-400  text-white">
      <h2><%= pluralize(category.errors.count, "error") %> found:</h2>

      <ul class="list-disc list-inside">
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="absolute bottom-0 w-full text-center bg-[#5fb523] p-4 text-white">
    <div class="w-full border-[1px] border-white py-4 cursor-pointer">
      <%= form.submit "Save", class: "w-full text-lg cursor-pointer" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="min-h-screen relative">
  <header class="w-full p-3 bg-[#3778c2] text-white text-lg flex justify-between">
    <nav>
      <i class="fa-solid fa-bars fa-lg"></i>
    </nav>
    <h1>Categories<h1>
    <%= button_to destroy_user_session_path, method: :delete do %>
      <i class="fa-solid fa-arrow-right-from-bracket fa-lg"></i>
    <% end %>
  </header>

  <ul class="w-full" id="categories">
    <% @categories.each do |category| %>
      <li class="w-[90%] mt-4 p-3 shadow mx-auto bg-white border-[1px] border-slate-200">
        <%= link_to category do %>
          <%= render category %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <div class="absolute bottom-0 w-full text-center bg-[#5fb523] p-4 text-white">
    <div class="w-full border-[1px] border-white py-4 cursor-pointer">
      <%= link_to "Add new category", new_category_path, class: "w-full text-lg" %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="min-h-screen relative">
  <header class="w-full p-3 bg-[#3778c2] text-white text-lg flex justify-between">
    <nav>
      <%= link_to categories_path do %>
        <i class="fa-solid fa-chevron-left fa-lg"></i>
      <% end %>
    </nav>
    <h1 class="ml-[-15px]">NEW CATEGORY<h1>
    <span></span>
  </header>

  <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<div class="min-h-screen relative">
  <header class="w-full p-3 bg-[#3778c2] text-white text-lg flex justify-between">
    <nav>
      <%= link_to root_path do %>
        <i class="fa-solid fa-chevron-left fa-lg"></i>
      <% end %>
    </nav>
    <h1 class="ml-[-15px]">Transactions<h1>
    <span></span>
  </header>

  <div class="w-full p-3 shadow mx-auto bg-white border-[1px] border-slate-200">
    <%= render @category %>
  </div>

  <ul class="w-full" id="categories">
    <% @category.payments.each do |payment| %>
      <li class="w-[90%] mt-4 py-3 px-5 shadow mx-auto bg-white border-[1px] border-slate-200">
        <div class="flex justify-between">
          <p><%= payment.name %></p>
          <p>$<%= payment.amount %></p>
        </div>
        <p class="text-gray-300 text-sm"><%= payment.created_at.strftime("%d %b %Y") %></p>
      </li>
    <% end %>
  </ul>

  <div class="absolute bottom-0 w-full text-center bg-[#5fb523] p-4 text-white">
    <div class="w-full border-[1px] border-white py-4 cursor-pointer">
      <%= link_to "Add new Transaction", new_payment_path, class: "w-full text-lg" %>
    </div>
  </div>
</div>